@startuml design_peer_eventstorming
!include common.puml
!include ../.gdiag/plantuml-libs/eventstorming/eventstorming-all.puml
package peer {
  command('StartLocalPeer')
  command('StopLocalPeer')
  event('LocalPeerStarted')
  event('LocalPeerStopped')
  aggregate('LocalPeer')
}
StartLocalPeer --> LocalPeerStarted : publishes
StopLocalPeer --> LocalPeerStopped : publishes
StartLocalPeer --> LocalPeer : creates
StopLocalPeer --> LocalPeer : creates
LocalPeerStarted -r-> LocalPeer : applied on
LocalPeerStopped -l-> LocalPeer : applied on
@enduml
