@startuml design_profile_eventstorming_create
!include common.puml
!include ../.gdiag/plantuml-libs/eventstorming/eventstorming-all.puml
package profile {
  command('CreateProfile')
  domain_event('ProfileCreated')
  domain_event('ProfileCardUpdated')
  aggregate('Profile')
  result('ProfileId')
}
CreateProfile --> ProfileCreated : generates
CreateProfile --> ProfileCardUpdated : generates
CreateProfile --> ProfileId : returns
CreateProfile --> Profile : creates
ProfileCreated -u-> Profile : applied on
ProfileCardUpdated -u-> Profile : applied on
@enduml

@startuml design_profile_eventstorming_import
!include common.puml
!include ../.gdiag/plantuml-libs/eventstorming/eventstorming-all.puml
package profile {
  command('ImportProfile')
  domain_event('ProfileCreated')
  aggregate('Profile')
  result('ProfileId')
  service('ProfileReferenceDeserializer')
}
ImportProfile --> ProfileCreated : generates
ImportProfile --> Profile : creates
ImportProfile -r-> ProfileId : returns
ImportProfile -l-> ProfileReferenceDeserializer : deserializes the reference
ProfileCreated -r-> Profile : applied on
@enduml

@startuml design_profile_eventstorming_update_profile_card
!include common.puml
!include ../.gdiag/plantuml-libs/eventstorming/eventstorming-all.puml
package profile {
  command('UpdateProfileCard')
  domain_event('ProfileCardUpdated')
  aggregate('Profile')
}
UpdateProfileCard --> ProfileCardUpdated : generates
UpdateProfileCard --> Profile : get
ProfileCardUpdated -r-> Profile : applied on
@enduml

@startuml design_profile_eventstorming_delete
!include common.puml
!include ../.gdiag/plantuml-libs/eventstorming/eventstorming-all.puml
package profile {
  command('DeleteProfile')
  domain_event('ProfileDeleted')
  aggregate('Profile')
}
DeleteProfile --> ProfileDeleted : generates
DeleteProfile --> Profile : deletes
ProfileDeleted -r-> Profile : applied on
@enduml

@startuml design_profile_eventstorming_get_serialized_reference
!include common.puml
!include ../.gdiag/plantuml-libs/eventstorming/eventstorming-all.puml
package profile {
  query('GetSerializedProfileReference')
  aggregate('Profile')
  service('ProfileReferenceSerializer')
  result('SerializedProfileReference')
}
GetSerializedProfileReference --> Profile : get
GetSerializedProfileReference --> ProfileReferenceSerializer : serializes the reference
GetSerializedProfileReference -r-> SerializedProfileReference : returns
@enduml

@startuml design_profile_eventstorming_load_profiles
!include common.puml
!include ../.gdiag/plantuml-libs/eventstorming/eventstorming-all.puml
package peer {
  domain_event('LocalPeerStarted')
}
package profile {
  process('ProfilesLoader')
  domain_event('ProfileCreated')
  integration_event('ProfilesLoaded') 
  aggregate('Profile')
}
LocalPeerStarted --> ProfilesLoader : triggers
ProfilesLoader -r-> Profile : creates
ProfileCreated -u-> Profile : applied on
ProfilesLoader --> ProfileCreated : generates
ProfilesLoader --> ProfilesLoaded : generates
@enduml

@startuml design_profile_eventstorming_synchronize_profiles_manage
!include common.puml
!include ../.gdiag/plantuml-libs/eventstorming/eventstorming-all.puml
package profile {
  domain_event('ProfileCreated')
  domain_event('ProfileSynchronized')
  service('ProfileSynchronizerService')
  aggregate('Profile')
  process('ProfileSynchronizer')
}

ProfileCreated -d-> ProfileSynchronizer : triggers
ProfileSynchronizer --> Profile : get
ProfileSynchronizer -r-> ProfileSynchronizerService : manages the ongoing synchronization
ProfileSynchronizer --> ProfileSynchronized : generates
ProfileSynchronized -l-> Profile : applied on
@enduml

@startuml design_profile_eventstorming_synchronize_profiles_stop
!include common.puml
!include ../.gdiag/plantuml-libs/eventstorming/eventstorming-all.puml
package peer {
  domain_event('LocalPeerStopped')
}
package profile {
  process('ProfileSynchronizer')
  service('ProfileSynchronizerService')
  integration_event('ProfilesSynchronizationStopped')
}

LocalPeerStopped -d-> ProfileSynchronizer : triggers
ProfileSynchronizer -r-> ProfileSynchronizerService : stops the ongoing synchronizations
ProfileSynchronizer --> ProfilesSynchronizationStopped : generates
@enduml
