@startuml design_peer_eventstorming_start_local_peer
!include common.eventstorming.puml
package peer {
  Command('StartLocalPeer')
  DomainEvent('LocalPeerStarted')
  Aggregate('LocalPeer')
}
StartLocalPeer --> LocalPeerStarted : generates
StartLocalPeer --> LocalPeer : get
LocalPeerStarted -r-> LocalPeer : applied on
@enduml

@startuml design_peer_eventstorming_stop_local_peer
!include common.eventstorming.puml
package peer {
  Command('StopLocalPeer')
  DomainEvent('LocalPeerStopped')
  Aggregate('LocalPeer')
}
StopLocalPeer --> LocalPeerStopped : generates
StopLocalPeer --> LocalPeer : get
LocalPeerStopped -r-> LocalPeer : applied on
@enduml
