@startuml prototype_demo_container
!include common.c4model.puml
ExternalSystem("github_actions", "GitHub Actions", "The main CI/CD environment of the dorders platform.")
SystemBoundary("dorders", "dorders") {
  Container("inmemory_network", "In Memory Network", "A network of dorders nodes hosted in the container memory.", "nodejs")
}
github_actions -r-> inmemory_network : Relationship("creates, consumes and deletes", "docker")
@enduml
